# Project 04 data appending

In [1]:
import pandas as pd 
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [ ]:
import json
import pandas as pd
import requests

API_KEY = "47a22ce2c5e1ae43424d3af49890dd85"

def fetch_series_data(series_id):
    """
    Fetch observations for a given series ID from the FRED API.
    """
    url = f"https://api.stlouisfed.org/fred/series/observations"
    params = {
        "series_id": series_id,
        "api_key": API_KEY,
        "file_type": "json"
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        observations = data.get("observations", [])
        return pd.DataFrame(observations).rename(columns={"date": "Date", "value": series_id})
    else:
        print(f"Failed to fetch data for series {series_id}. Status code: {response.status_code}")
        return pd.DataFrame()

single_series_data=fetch_series_data("VIXCLS")[["Date","VIXCLS"]]
single_series_data["Date"]=pd.to_datetime(single_series_data["Date"])
# single_series_data.set_index("Date",inplace=True)
# if there is a '.' in the data, remove it
# single_series_data["VIXCLS"]=single_series_data["VIXCLS"].str.replace('.','')
single_series_data["VIXCLS"]=pd.to_numeric(single_series_data["VIXCLS"])
single_series_data.Date
# convert decimal format vixcls to number
# single_series_data["VIXCLS"][33:35]
# remove '.' from the data

ValueError: Unable to parse string "." at position 34

In [51]:
# load in ML-Dataset.csv
df = pd.read_csv("ML-Dataset.csv")
# convert OrderDate to datetime type
df["OrderDate"] = pd.to_datetime(df["OrderDate"])
# df["OrderDate"] = df["OrderDate"].dt.strftime('%Y-%m-%d')
# merge the two dataframes, take VIXCLS closest to the OrderDate
df = pd.merge_asof(
    df.sort_values("OrderDate"), 
    single_series_data.reset_index().sort_values("Date"), 
    left_on="OrderDate", 
    right_on="Date", 
    direction="nearest"
)
df

/var/folders/98/dzdn2lnj2qzdc79xf2_qdgpc0000gq/T/ipykernel_71851/166101815.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["OrderDate"] = pd.to_datetime(df["OrderDate"])

,RegionName,CountryName,State,City,PostalCode,WarehouseAddress,WarehouseName,EmployeeName,EmployeeEmail,EmployeePhone,...,CustomerEmail,CustomerPhone,Status,OrderDate,OrderItemQuantity,PerUnitPrice,TotalItemQuantity,index,Date,VIXCLS
0,North America,United States of America,Washington,Seattle,98199,2004 Charade Rd,Seattle Washington,Burkett Benjamin,BurkettBenjamin@gmail.com,26523655356,...,ha.lowe@intel.com,18920998222,Shipped,2013-06-21,119,739.99,123,6123,2013-06-21,1890.0
1,North America,United States of America,California,South San Francisco,99236,2011 Interiors Blvd,San Francisco,Amber Rose,amber.rose@example.com,6505079822,...,tamatha.delgado@dish.com,9017715131,Canceled,2013-06-21,130,97.88,34,6123,2013-06-21,1890.0
2,Australia,Australia,New South Wales,Sydney,2901,12-98 Victoria Street,Sydney,Gray Elijiah,GrayElijiah@gmail.com,17100242216,...,ginger.atkinson@nordstrom.com,913855683806,Pending,2013-06-21,112,579.99,105,6123,2013-06-21,1890.0
3,North America,Mexico,Distrito Federal,Mexico City,11932,Mariano Escobedo 9991,Mexico City,Morway Tanya,MorwayTanya@gmail.com,444227859,...,vernia.hayes@drhorton.com,9920257,Canceled,2013-06-21,122,699.89,94,6123,2013-06-21,1890.0
4,Asia,China,Beijing,Beijing,190518,40-5-12 Laogianggen,Beijing,Sahoo Adil,SahooAdil@gmail.com,1582707843,...,SalterJason@gmail.com,41336173728,Pending,2013-06-21,84,2042.69,214,6123,2013-06-21,1890.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,North America,United States of America,Washington,Seattle,98199,2004 Charade Rd,Seattle Washington,Clukey Elijian,ClukeyElijian@gmail.com,26510443827,...,hisako.herrera@tysonfoods.com,6577099912,Canceled,2017-11-01,89,43.99,136,7261,2017-11-01,102.0
396,Asia,China,Beijing,Beijing,190518,40-5-12 Laogianggen,Beijing,Ozark Travis,OzarkTravis@gmail.com,68811771,...,wendell.massey@bbt.com,74014943283,Canceled,2017-11-01,58,1499.89,178,7261,2017-11-01,102.0
397,Asia,China,Beijing,Beijing,190518,40-5-12 Laogianggen,Beijing,Ruiz Ricardo,RuizRicardo@gmail.com,16298665789,...,SaadaAdell@gmail.com,339893438,Shipped,2017-11-01,42,2774.98,213,7261,2017-11-01,102.0
398,North America,United States of America,Washington,Seattle,98199,2004 Charade Rd,Seattle Washington,Buccheri Joseph,BuccheriJoseph@gmail.com,26531027628,...,gonzalo.stone@lowes.com,7877876654,Shipped,2017-11-01,78,299.89,121,7261,2017-11-01,102.0
399,North America,United States of America,New Jersey,South Brunswick,50090,2007 Zagora St,New Jersy,Ellis Washington,ellis.washington@example.com,6501246234,...,margart.mccall@unitedhealthgroup.com,7877019201,Shipped,2017-11-01,146,873.98,22,7261,2017-11-01,102.0